In [1]:
import pandas as pd
import numpy as np

In [2]:
cereal_df = pd.read_csv("cereal.csv")
cereal_df.head(7)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.0,1.00,33.174094

In [3]:
cereal_df.drop(['name'], axis=1)

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [4]:
cereal_df.type.unique()

array(['C', 'H'], dtype=object)

In [5]:
cereal_df.mfr.unique()

array(['N', 'Q', 'K', 'R', 'G', 'P', 'A'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
## LAbel Encoder helps in encoding the object type variables into binary(integers)

le = LabelEncoder()
cereals_df1 = cereal_df
cereals_df1.mfr = le.fit_transform(cereals_df1.mfr)
cereals_df1.type = le.fit_transform(cereals_df1.type)
cereals_df1

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,3,0,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,5,0,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,2,0,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,2,0,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,6,0,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,1,0,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,1,0,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,6,0,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,1,0,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,1,0,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [7]:
cereals_df1.mfr

0     3
1     5
2     2
3     2
4     6
     ..
72    1
73    1
74    6
75    1
76    1
Name: mfr, Length: 77, dtype: int32

In [8]:
y = cereals_df1.rating
X = cereals_df1.drop(['rating', 'name'], axis = 'columns')

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [10]:
from sklearn.linear_model import LinearRegression
model_1 = LinearRegression()
model_1.fit(X_train, y_train)
model_1.score(X_test, y_test)

0.9999999999999986

In [12]:
## Mean Absolute Error shows the magnitude of difference between the prediction of the model and the true value of the data
from sklearn.metrics import mean_absolute_error
Y_preds = model_1.predict(X_test)
model_1_mae = mean_absolute_error(Y_preds, y_test)
print("MAE: ", model_1_mae)

MAE:  3.2558513307634485e-07

In [13]:
from sklearn.tree import DecisionTreeRegressor
model_2 = DecisionTreeRegressor()
model_2.fit(X_train, y_train)
model_2.score(X_test, y_test)

0.696092906582638

In [14]:
model_2_predictions = model_1.predict(X_test)
model_2_mae = mean_absolute_error(y_test, model_2_predictions)
print("MAE: ", model_2_mae)

MAE:  3.2558513307634485e-07

In [15]:
from sklearn.ensemble import RandomForestRegressor
model_3 = RandomForestRegressor(n_estimators=100)
model_3.fit(X_train, y_train)
model_3.score(X_test, y_test)

0.8601146612235822

In [16]:
model_3_predictions = model_3.predict(X_test)
model_3_mae = mean_absolute_error(y_test, model_3_predictions)
print("MAE: ", model_3_mae)

MAE:  2.675263885625009

In [21]:
model_1.predict(X_test)

array([34.13976434, 40.69232033, 51.59219287, 39.25919741, 40.56015888,
       45.81171581, 19.82357254, 27.75330099, 22.3965128 , 32.20758139,
       22.7364463 , 28.02576455, 28.74241358, 45.32807431, 49.51187444,
       37.03856184])

In [22]:
y_test

45    34.139765
49    40.692320
75    51.592193
58    39.259197
62    40.560159
34    45.811716
12    19.823573
73    27.753301
18    22.396513
24    32.207582
14    22.736446
29    28.025765
37    28.742414
41    45.328074
56    49.511874
7     37.038562
Name: rating, dtype: float64

In [23]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline

In [24]:
## Pipeline Creation
## 1. Data preprocessing using standardscaler
## 2. Reduce dimension using PCA
## 3. Apply classifier

In [28]:
pipeline_lr = Pipeline([('scaler_1', StandardScaler()),
                       ('pca_1', PCA(n_components=2)),
                       ('lr_classifier', LinearRegression())])
pipeline_dt = Pipeline([('scaler_2', StandardScaler()),
                       ('pca_2', PCA(n_components=2)),
                        ('dt_classifier', DecisionTreeRegressor())])
pipeline_rf = Pipeline([('scaler_3', StandardScaler()),
                       ('pca_3', PCA(n_components=2)),
                       ('rf_classifier', RandomForestRegressor())])

pipeline_model = (pipeline_lr, pipeline_dt, pipeline_rf)

In [29]:
pipeline_dict = {0: "Linear Regression", 1: "DecisionTreeRegressor", 2: "Random Forest Regression"}
for pipe in pipeline_model:
    pipe.fit(X_train, y_train)
    
for i,model in enumerate(pipeline_model):
    print("{} test accuracy {}".format(pipeline_dict[i], model.score(X_test, y_test)))

Linear Regression test accuracy 0.2663049714310657
DecisionTreeRegressor test accuracy 0.08650606841179176
Random Forest Regression test accuracy 0.4812426250914874

In [30]:
best_accuracy=0.0
best_classifier=0
best_pipeline=""

for i,model in enumerate(pipeline_model):
    if model.score(X_test, y_test)>best_accuracy:
        best_accuracy=model.score(X_test, y_test)
        best_pipeline=model
        best_classifier=i
        
print("Classifier with best accuracy: {} ".format(pipeline_dict[best_classifier]))

Classifier with best accuracy: Random Forest Regression